[package]
name = "fleck"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Leiser Fern√°ndez Gallo"]
repository = "https://github.com/leiserfg/fleck"
homepage = "https://github.com/leiserfg/fleck"
license = "MIT"
description = "Reimplementation of Latex Coffee Steins in typst"
keywrods = ["coffee", "stains", "draw"]
exclude = ["example.pdf", "example.png"]
